{{- define "argoconfig.application.tpl" -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ template "common.metadata" . }}
spec:
  project: "default"
  source: {}
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy: {}
{{- end -}}
{{- define "argoconfig.application" -}}
{{- include "common.util.merge" (append . "argoconfig.application.tpl") -}}
{{- end -}}
