{{- $defaults := .Values.apps.defaults -}}
{{- range $name, $app := .Values.apps -}}
{{- if $app.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "argoconfig.fullname" $ }}-{{ $name }}
  {{- with (default $defaults.namespace $app.namespace) }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "argoconfig.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  project: {{ if $app.projectOverride }}{{ $app.projectOverride }}{{ else }}{{ include "argoconfig.fullname" $ }}{{ end }}
  source:
    {{- merge $app.source $defaults.source | toYaml | nindent 4 }}
  destination:
    {{- merge $app.destination $defaults.destination | toYaml | nindent 4 }}
    {{- with $app.values }}
    helm:
      values: |-
        {{- . | toYaml | nindent 8 }}
    {{- end }}
  {{- if $app.syncPolicy }}
  syncPolicy:
    {{- $app.syncPolicy | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
{{ end }}
