{{- if .Values.appProject.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ include "argoconfig.fullname" . }}
  {{- with .Values.appProject.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "argoconfig.labels" . | nindent 4 }}
spec:
  clusterResourceWhitelist:
    {{- .Values.appProject.clusterResourceWhitelist | toYaml | nindent 4 }}
  destinations:
    {{- .Values.appProject.destinations | toYaml | nindent 4 }}
  sourceRepos:
    {{- .Values.appProject.sourceRepos | toYaml | nindent 4 }}
{{- end }}
