{{- $defaults := .Values.clusters.defaults -}}
{{- range $name, $cluster := .Values.clusters }}
{{- if $cluster.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  {{- with (default $defaults.namespace $cluster.namespace) }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "argoconfig.labels" $ | nindent 4 }}
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: {{ $name }}
  server: {{ $cluster.server }}
  config: |
    {{- merge $cluster.config $defaults.config | toJson | nindent 4 -}}
{{- end }}
{{ end }}
