# dex -- [dex](https://github.com/dexidp/dex/) ([example](./examples/dex.yaml))
# @default -- -
dex:
  # dex.enabled -- Enable dex
  enabled: false
  name: dex
  destination:
    # dex.destination.namespace -- Namespace
    namespace: "infra-dex"
  # dex.repoURL -- Repo URL
  # @default -- [repo](https://charts.helm.sh/stable/)
  repoURL: "https://charts.helm.sh/stable/"
  # dex.chart -- Chart
  chart: "dex"
  # dex.targetRevision -- [dex Helm chart](https://github.com/helm/charts/tree/master/stable/dex/) version
  targetRevision: "2.10.*"
  # dex.values -- Helm values
  # @default -- [upstream values](https://github.com/helm/charts/tree/master/stable/dex/values.yaml)
  values: {}

# gangway -- [gangway](https://github.com/heptiolabs/gangway/) ([example](./examples/gangway.yaml))
# @default -- -
gangway:
  # gangway.enabled -- Enable gangway
  enabled: false
  name: gangway
  destination:
    # gangway.destination.namespace -- Namespace
    namespace: "infra-gangway"
  # gangway.repoURL -- Repo URL
  # @default -- [repo](https://charts.helm.sh/stable/)
  repoURL: "https://charts.helm.sh/stable/"
  # gangway.chart -- Chart
  chart: "gangway"
  # gangway.targetRevision -- [gangway Helm chart](https://github.com/helm/charts/tree/master/stable/gangway/) version
  targetRevision: "0.4.*"
  # gangway.values -- Helm values
  # @default -- [upstream values](https://github.com/helm/charts/tree/master/stable/gangway/values.yaml)
  values: {}

# vault -- [vault](https://github.com/hashicorp/vault/) ([example](./examples/vault.yaml))
# @default -- -
vault:
  # vault.enabled -- Enable vault
  enabled: false
  name: vault
  destination:
    # vault.destination.namespace -- Namespace
    namespace: "infra-vault"
  # vault.repoURL -- Repo URL
  # @default -- [repo](https://helm.releases.hashicorp.com/)
  repoURL: "https://helm.releases.hashicorp.com/"
  # vault.chart -- Chart
  chart: "vault"
  # vault.targetRevision -- [vault Helm chart](https://github.com/hashicorp/vault-helm) version
  targetRevision: "0.8.*"
  # vault.values -- Helm values
  # @default -- [upstream values](https://github.com/hashicorp/vault-helm/tree/master/values.yaml)
  values: {}

# falco -- [falco](https://github.com/falcosecurity/falco/) ([example](./examples/falco.yaml))
# @default -- -
falco:
  # falco.enabled -- Enable falco
  enabled: false
  name: falco
  destination:
    # falco.destination.namespace -- Namespace
    namespace: "infra-falco"
  # falco.repoURL -- Repo URL
  # @default -- [repo](https://falcosecurity.github.io/charts)
  repoURL: "https://falcosecurity.github.io/charts"
  # falco.chart -- Chart
  chart: "falco"
  # falco.targetRevision -- [falco Helm chart](https://github.com/falcosecurity/charts/tree/master/falco) version
  targetRevision: "1.5.*"
  # falco.values -- Helm values
  # @default -- [upstream values](https://github.com/falcosecurity/charts/blob/master/falco/values.yaml)
  values: {}

# falcosidekick -- [falcosidekick](https://github.com/falcosecurity/falcosidekick/) ([example](./examples/falcosidekick.yaml))
# @default -- -
falcosidekick:
  # falcosidekick.enabled -- Enable falcosidekick
  enabled: false
  name: falcosidekick
  destination:
    # falcosidekick.destination.namespace -- Namespace
    namespace: "infra-falco"
  # falcosidekick.repoURL -- Repo URL
  # @default -- [repo](https://falcosecurity.github.io/charts)
  repoURL: "https://falcosecurity.github.io/charts"
  # falcosidekick.chart -- Chart
  chart: "falcosidekick"
  # falcosidekick.targetRevision -- [falcosidekick Helm chart](https://github.com/falcosecurity/charts/tree/master/falcosidekick) version
  targetRevision: "0.1.*"
  # falcosidekick.values -- Helm values
  # @default -- [upstream values](https://github.com/falcosecurity/charts/blob/master/falcosidekick/values.yaml)
  values: {}

# falcoExporter -- [falco-exporter](https://github.com/falcosecurity/falco-exporter/) ([example](./examples/falco-exporter.yaml))
# @default -- -
falcoExporter:
  # falcoExporter.enabled -- Enable falco-exporter
  enabled: false
  name: falco-exporter
  destination:
    # falcoExporter.destination.namespace -- Namespace
    namespace: "infra-falco"
  # falcoExporter.repoURL -- Repo URL
  # @default -- [repo](https://falcosecurity.github.io/charts)
  repoURL: "https://falcosecurity.github.io/charts"
  # falcoExporter.chart -- Chart
  chart: "falco-exporter"
  # falcoExporter.targetRevision -- [falco Helm chart](https://github.com/falcosecurity/charts/tree/master/falco-exporter) version
  targetRevision: "0.4.*"
  # falcoExporter.values -- Helm values
  # @default -- [upstream values](https://github.com/falcosecurity/charts/blob/master/falco-exporter/values.yaml)
  values: {}

# gatekeeper -- [gatekeeper](https://github.com/open-policy-agent/gatekeeper) ([example](./examples/gatekeeper.yaml))
# @default -- -
gatekeeper:
  # gatekeeper.enabled -- Enable falco
  enabled: false
  name: gatekeeper
  destination:
    # gatekeeper.destination.namespace -- Namespace
    namespace: "infra-gatekeeper"
  # gatekeeper.repoURL -- Repo URL
  # @default -- [repo](https://open-policy-agent.github.io/gatekeeper/charts)
  repoURL: "https://open-policy-agent.github.io/gatekeeper/charts"
  # gatekeeper.chart -- Chart
  chart: "gatekeeper"
  # gatekeeper.targetRevision -- [gatekeeper Helm chart](https://github.com/open-policy-agent/gatekeeper/tree/master/charts/gatekeeper) version
  targetRevision: "3.2.2"
  # gatekeeper.values -- Helm values
  # @default -- [upstream values](https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/values.yaml)
  values: {}
