image:
  # image.repository -- Image repository
  repository: ubcctlt/barman
  # image.tag -- Image tag
  tag: "latest"
  # image.pullPolicy -- Image pull policy
  pullPolicy: Always

# resources -- Resource limits and requests
resources: {}

persistence:
  data:
    # persistence.data.enabled -- Enable persistent storage for backup data
    enabled: true
    # persistence.data.accessMode -- Access mode for persistent storage
    accessMode: ReadWriteOnce
    # persistence.data.size -- Size of storage volume
    size: 20Gi
    # persistence.data.storageClass -- Storage class
    storageClass: ""
  recover:
    # persistence.recover.enabled -- Enable persistent storage for recovery
    enabled: false
    # persistence.recover.accessMode -- Access mode for persistent storage
    accessMode: ReadWriteOnce
    # persistence.recover.size -- Size of storage volume
    size: 4Gi
    # persistence.recover.storageClass -- Storage class
    storageClass: ""

barman:
  # barman.backupMethod -- Barman backup method
  backupMethod: postgres
  # barman.backupOptions -- Barman backup options
  backupOptions: concurrent_backup
  # barman.backupDir -- Barman home directory
  backupDir: /var/lib/barman
  # barman.barmanUser -- Barman user
  barmanUser: barman
  # barman.compression -- Barman backup compression
  compression: gzip
  # barman.retentionPolicy -- Barman retention policy
  retentionPolicy: "RECOVERY WINDOW of 1 MONTH"
  # barman.lastBackupMaximumAge -- Barman last backup maximum age
  lastBackupMaximumAge: "1 day"
  # barman.backupSchedule -- Barman backup schedule
  backupSchedule: "0 4 * * *"
  # barman.databaseSlotName -- Database slot name to be created/used
  databaseSlotName: barman

  backups:
      # barman.backups[0].retentionPolicy -- Barman retention policy
    - retentionPolicy: "RECOVERY WINDOW of 1 MONTH"
      # barman.backups[0].backupMethod -- Barman backup method
      backupMethod: postgres
      # barman.backups[0].databaseSlotName -- Database slot name to be created/used
      databaseSlotName: barman
      # barman.backups[0].lastBackupMaximumAge -- Barman last backup maximum age
      lastBackupMaximumAge: "1 day"
      postgresql:
        # barman.backups[0].postgresql.host -- Postgresql host
        host: postgresql
        # barman.backups[0].postgresql.port -- Postgresql port
        port: 5432
        # barman.backups[0].postgresql.superUser -- Postgresql super user
        superUser: postgres
        # barman.backups[0].postgresql.superUserPassword -- Postgresql super user password
        superUserPassword: postgres
        # barman.backups[0].postgresql.superUserDatabase -- Postgresql super user database
        superUserDatabase: postgres
        # barman.backups[0].postgresql.replicationUser -- Postgresql replication user
        replicationUser: barman
        # barman.backups[0].postgresql.replicationPassword -- Postgresql replication password
        replicationPassword: barman

prometheus:
  # prometheus.enabled -- Enable Prometheus integration
  enabled: true
  service:
    # prometheus.service.name -- Prometheus exporter service name
    name: barman-exporter
    # prometheus.service.internalPort -- Prometheus exporter service internal port
    internalPort: 9780
    # prometheus.service.externalPort -- Prometheus exporter service external port
    externalPort: 9780
    # prometheus.service.type -- Prometheus exporter service type
    type: ClusterIP
  serviceMonitor:
    # prometheus.serviceMonitor.extraLabels -- Labels to add to service monitor
    extraLabels: {}
    # prometheus.serviceMonitor.interval -- Interval at which metrics should be scraped
    interval: "30s"
    # prometheus.serviceMonitor.metricRelabelings -- MetricRelabelConfigs to apply to samples before ingestion
    metricRelabelings: []
    # prometheus.serviceMonitor.relabelings -- RelabelConfigs to apply to samples before scraping
    relabelings: []
