apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timed.fullname" . }}-backend
  labels:
    {{- include "timed.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  EMAIL_URL: {{ .Values.backend.settings.emailUrl | quote }}
  DJANGO_ALLOWED_HOSTS: {{ join "," .Values.ingress.hosts | default "localhost" }}
  DJANGO_HOST_DOMAIN: {{ mustFirst .Values.ingress.hosts | default "localhost" | quote }}
  DJANGO_HOST_PROTOCOL: http{{- if .Values.ingress.tls }}s{{- end }}
  DJANGO_DEFAULT_FROM_EMAIL: {{ .Values.backend.settings.emailFrom | quote }}
  DJANGO_SERVER_EMAIL: {{ .Values.backend.settings.serverEmail | quote }}
  DJANGO_DATABASE_NAME: {{ .Values.postgresql.postgresqlDatabase | quote }}
  DJANGO_DATABASE_USER: {{ .Values.postgresql.postgresqlUsername | quote }}
  DJANGO_DATABASE_PORT: {{ .Values.postgresql.service.port | quote }}
  DJANGO_WORK_REPORT_PATH: {{ .Values.backend.settings.workReportPath | quote }}
  DJANGO_OIDC_USERINFO_ENDPOINT: {{ .Values.auth.oidc.userinfoEndpoint | quote }}
  DJANGO_OIDC_CLIENT_ID: {{ .Values.auth.oidc.client.id | quote }}
  DJANGO_OIDC_CREATE_USER: {{ .Values.auth.oidc.createUser | quote }}
  DJANGO_OIDC_USERNAME_CLAIM: {{ .Values.auth.oidc.claims.username | quote }}
  DJANGO_OIDC_EMAIL_CLAIM: {{ .Values.auth.oidc.claims.email | quote }}
  DJANGO_OIDC_FIRSTNAME_CLAIM: {{ .Values.auth.oidc.claims.firstname | quote }}
  DJANGO_OIDC_LASTNAME_CLAIM: {{ .Values.auth.oidc.claims.lastname | quote }}
  DJANGO_OIDC_ADMIN_LOGIN_REDIRECT_URL: {{ .Values.auth.oidc.adminLoginRedirectUrl | quote }}
{{- if .Values.auth.oidc.introspect.enabled }}
  DJANGO_OIDC_CHECK_INTROSPECT: "True"
  DJANGO_OIDC_INTROSPECT_ENDPOINT: {{ .Values.auth.oidc.introspect.endpoint | quote }}
{{- else }}
  DJANGO_OIDC_CHECK_INTROSPECT: "False"
{{- end }}
{{- if .Values.postgresql.enabled }}
  DJANGO_DATABASE_HOST: {{ include "timed.postgresql.fullname" . | quote }}
{{- else }}
  DJANGO_DATABASE_HOST: {{ .Values.postgresql.service.host | quote }}
{{- end }}
{{- if .Values.redmine.enabled }}
  DJANGO_REDMINE_URL: {{ .Values.redmine.url | quote }}
  DJANGO_REDMINE_HTACCESS_USER: {{ .Values.redmine.htaccessUser | quote }}
  DJANGO_REDMINE_SPENTHOURS_FIELD: {{ .Values.redmine.spenthoursField | quote }}
{{- end }}
  UWSGI_MAX_REQUESTS: {{ .Values.backend.settings.uwsgi.maxRequests | quote }}
  UWSGI_HARAKIRI: {{ .Values.backend.settings.uwsgi.harakiri | quote }}
  UWSGI_PROCESSES: {{ .Values.backend.settings.uwsgi.processes | quote }}
{{- if .Values.backend.settings.admins }}
  DJANGO_ADMINS: {{ join "," .Values.backend.settings.admins | quote }}
{{- end }}
