apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timed.fullname" . }}-backend
  labels:
    {{- include "timed.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  EMAIL_URL: {{ .Values.backend.settings.emailUrl | quote }}
  DJANGO_ALLOWED_HOSTS: {{ join "," .Values.ingress.hosts | default "localhost" }}
  DJANGO_HOST_DOMAIN: {{ mustFirst .Values.ingress.hosts | default "localhost" | quote }}
  DJANGO_HOST_PROTOCOL: http{{- if .Values.ingress.tls }}s{{- end }}
  DJANGO_DEFAULT_FROM_EMAIL: {{ .Values.backend.settings.emailFrom | quote }}
  DJANGO_SERVER_EMAIL: {{ .Values.backend.settings.serverEmail | quote }}
  DJANGO_DATABASE_NAME: {{ .Values.postgresql.postgresqlDatabase | quote }}
  DJANGO_DATABASE_USER: {{ .Values.postgresql.postgresqlUsername | quote }}
  DJANGO_DATABASE_PORT: {{ .Values.postgresql.service.port | quote }}
  DJANGO_WORK_REPORT_PATH: {{ .Values.backend.settings.workReportPath | quote }}
{{- if .Values.postgresql.enabled }}
  DJANGO_DATABASE_HOST: {{ include "timed.postgresql.fullname" . | quote }}
{{- else }}
  DJANGO_DATABASE_HOST: {{ .Values.postgresql.service.host | quote }}
{{- end }}
{{- if .Values.auth.ldap.enabled }}
  DJANGO_AUTH_LDAP_ENABLED: true
  DJANGO_AUTH_LDAP_USER_ATTR_MAP: {{ .Values.auth.ldap.userAttrMap | quote }}
  DJANGO_AUTH_LDAP_SERVER_URI: {{ .Values.auth.ldap.serverUri | quote }}
  DJANGO_AUTH_LDAP_BIND_DN: {{ .Values.auth.ldap.bindDn | quote }}
  DJANGO_AUTH_LDAP_USER_DN_TEMPLATE: {{ .Values.auth.ldap.userDnTemplate | quote }}
{{- end }}
