# This shows a secret as a pre-install hook.
# A pre-install hook is run before the rest of the chart is loaded.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timed.fullname" . }}-django
  labels:
    {{- include "timed.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  {{ if .Values.backend.service.secret }}
  DJANGO_SECRET_KEY: {{ .Values.backend.service.secret | b64enc | quote }}
  {{ else }}
  DJANGO_SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
