apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timed.fullname" . }}-backend
  labels:
    {{- include "timed.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  {{ if .Values.backend.service.secret }}
  DJANGO_SECRET_KEY: {{ .Values.backend.service.secret | b64enc | quote }}
  {{ else }}
  DJANGO_SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
  {{ if .Values.auth.ldap.enabled }}
  DJANGO_AUTH_LDAP_BIND_PASSWORD: {{ .Values.auth.ldap.password | b64enc | quote }}
  {{ end }}
  {{ if .Values.redmine.enabled }}
  DJANGO_REDMINE_APIKEY: {{ .Values.redmine.apiKey | quote }}
  DJANGO_REDMINE_HTACCESS_PASSWORD: {{ .Values.redmine.htaccessPassword | quote }}
  {{ end }}
