repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v0.12.0
    hooks:
      - id: helm-docs
  - repo: local
    hooks:
      - id: update-readme
        name: Update root README.md
        language: script
        entry: ./hack/update-readme.sh
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
