apiVersion: v1
kind: Service
metadata:
  name: {{ include "rmd.fullname" . }}
  labels:
    {{- include "rmd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rmd.service.type }}
  ports:
    - port: {{ .Values.rmd.service.externalPort }}
      targetPort: {{ .Values.rmd.service.internalPort }}
      protocol: TCP
  selector:
    {{- include "rmd.selectorLabels" . | nindent 4 }}
