---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentry
  namespace: {{ .Values.spec.metadata.namespace }}
  labels:
    {{ include "common.labels.standard" . | nindent 4 }}
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: sentry
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision | default "HEAD" }}
    helm:
      values: |-
        user:
          {{- .Values.user | nindent 1 }}

        ingress:
          {{- .Values.ingress | nindent 1 }}

        clickhouse:
          clickhouse:
            {{ .Values.clickhouse | nindent 2 }}

        kafka:
          {{- .Values.kafka | nindent 1 }}

        postgresql:
          postgresqlPassword: {{ .Values.postgresql.postgresqlPassword | quote }}
          persistence:
            enabled: true

        rabbitmq:
          {{- .Values.rabbitmq | nindent 2 }}

        redis:
          cluster:
            slaveCount: {{ .Values.redis.cluster.slaveCount }}

        sentry:
          worker:
            {{- .Values.sentry.worker | nindent 2 }}

        system:
          secretKey: {{ .Values.system.secretKey | quote }}

        zookeeper:
          persistence:
            enabled: true
