{{ template "argoconfig.application" (list . "sentry-apps") }}

{{- define "sentry-apps" }}
{{- $name := (template "common.name") -}}
metadata:
  name: {{ .Values.spec.metadata.name | default $name }}
spec:
  destination:
    {{- with .Values.spec.destination.namespace }}
    namespace: {{ . }}
    {{- end }}
    {{- with .Values.spec.destination.server }}
    server: {{ . }}
    {{- end }}
  source:
    chart: {{ .Values.spec.source.chart }}
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision | quote }}
    helm:
      values: |-
        nameOverride: {{ template "common.fullname" }}

        user:
          {{- .Values.user | toYaml | nindent 10 }}

        ingress:
          {{- .Values.ingress | toYaml | nindent 10 }}

        clickhouse:
          clickhouse:
            {{- .Values.clickhouse | toYaml | nindent 12 }}

        kafka:
          {{- .Values.kafka | toYaml | nindent 10 }}

        postgresql:
          postgresqlPassword: {{ .Values.postgresql.postgresqlPassword | quote }}
          persistence:
            enabled: true

        rabbitmq:
          {{- .Values.rabbitmq | toYaml | nindent 10 }}

        redis:
          cluster:
            slaveCount: {{ .Values.redis.cluster.slaveCount }}

        sentry:
          worker:
            {{- .Values.sentry.worker | toYaml | nindent 12 }}

        system:
          secretKey: {{ .Values.system.secretKey | quote }}

        zookeeper:
          persistence:
            enabled: true
{{- end }}
