spec:
  metadata:
    # spec.metadata.name -- name for the ArgoCD application
    name: sentry
    # spec.metadata.namespace -- namespace for the ArgoCD application
    namespace: argocd
  destination:
    # spec.destination.namespace -- namespace for Sentry
    namespace: sentry
  # spec.project -- project to deploy the ArgoCD application to
  project: default
  source:
    # spec.source.chart -- name of the Chart for Sentry
    chart: sentry
    # spec.source.path -- path of the Chart for Sentry when using Git repository
    path: ""
    # spec.source.repoURL -- Chart museum to get Sentry
    repoURL: "https://sentry-kubernetes.github.io/charts"
    # spec.source.targetRevision -- revision of the chart to use for Sentry
    # targetRevision:

user:
  # user.create -- if true, creates the user defined by email and password.
  create: true
  # user.email -- Admin user email
  email: admin@sentry.local
  # user.password -- Admin user password
  password: admin

ingress:
  # ingress.enabled -- if true, enables the ingress configuration.
  enabled: false
  # ingress.hostname -- hostname to use
  hostname: ""

clickhouse:
  # clickhouse.replicas -- total number of clickhouse replicas
  replicas: 1

# kakfa -- Kafka configuration
# @defaults -- See [bitnami/kafka](https://github.com/bitnami/charts/tree/master/bitnami/kafka/)
kafka: {}

rabbitmq:
  # rabbitmq.enabled -- enable RabbitMQ
  # Redis will be used instead.
  enabled: false

relay:
  # relay.replicas -- total number of relay replicas (use 0 when bootstrapping)
  replicas: 1

# redis -- Redis settigs
# @defaults -- See [bitnami/redis](https://github.com/bitnami/charts/tree/master/bitnami/redis) chart
redis:
  enabled: true

  cluster:
    # redis.cluster.slaveCount -- number of followers in the Redis cluster
    slaveCount: 1

sentry:
  worker:
    # sentry.worker.replicas -- total number of sentry worker replicas
    replicas: 1

postgresql:
  # postgresql.postgresqlPassword -- (string) password used to access the database
  postgresqlPassword:

# config -- extra configuration for some config maps
# @defaults -- See [values.yaml](https://github.com/sentry-kubernetes/charts/tree/develop/sentry) of upstream project
config: {}

system:
  # system.secretKey -- (string) secret key used for the session.
  # Changing it invalidates all the current sessions.
  secretKey:
