apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "back8sup.fullname" . }}
  labels:
    {{- include "back8sup.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
