apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "customerCenter.fullname" . }}-backend
  labels:
    {{- include "customerCenter.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  NODE_ENV: {{ .Values.backend.settings.nodeEnv | default "production" | quote }}
  DEBUG: {{ .Values.backend.settings.debug | quote }}
  APPLICATION_NAME: {{ .Values.backend.settings.appName | quote }}
  APPLICATION_HOST: {{ .Values.backend.settings.appHost | quote }}
  IDP_HOST: {{ .Values.backend.settings.idp.host | quote }}
  IDP_TOKEN_PATH: {{ .Values.backend.settings.idp.tokenPath | quote }}
  IDP_CLIENT_ID: {{ .Values.backend.settings.idp.clientID | quote }}
  TIMED_HOST: {{ .Values.backend.settings.timed.host | quote }}
  TIMED_PREFIX: {{ .Values.backend.settings.timed.prefix | quote }}
{{- if .Values.postgresql.enabled }}
  POSTGRES_HOST: {{ include "customerCenter.postgresql.fullname" . | quote }}
  POSTGRES_DATABASE: {{ .Values.postgresql.postgresqlDatabase | quote }}
  POSTGRES_USERNAME: {{ .Values.postgresql.postgresqlUsername | quote }}
{{- end }}
{{- if .Values.redis.enabled }}
  REDIS_HOST: {{  include "customerCenter.redis.fullname" . }}-master
{{- end }}
  SMTP_HOST: {{ .Values.backend.settings.smtp.host | quote }}
  SMTP_FROM: {{ .Values.backend.settings.smtp.from | quote }}
  SMTP_TO: {{ .Values.backend.settings.smtp.to | quote }}
  SMTP_SECURE: {{ .Values.backend.settings.smtp.secure | quote }}
  SMTP_REQUIRE_TLS: {{ .Values.backend.settings.smtp.requireTLS | quote }}
  AUTH_ROLE_ADMIN: {{ .Values.backend.settings.auth.roleAdmin | quote }}
  AUTH_ROLE_EMPLOYEE: {{ .Values.backend.settings.auth.roleEmployee | quote }}
  AUTH_EXPIRE_PASSWORD: {{ .Values.backend.settings.auth.expirePassword | quote }}
  AUTH_USERS_SEARCH_BASE: {{ .Values.backend.settings.auth.usersSearchBase | quote }}
  AUTH_USERS_SEARCH_FILTER: {{ .Values.backend.settings.auth.usersSearchFilter | quote }}
  AUTH_USERS_GROUPSEARCH_BASE: {{ .Values.backend.settings.auth.usersGroupSearchBase | quote }}
  AUTH_USERS_GROUPSEARCH_FILTER: {{ .Values.backend.settings.auth.usersGroupSearchFilter | quote }}
  AUTH_CUSTOMERS_SEARCH_BASE: {{ .Values.backend.settings.auth.usersCustomersSearchBase | quote }}
  AUTH_CUSTOMERS_SEARCH_FILTER: {{ .Values.backend.settings.auth.usersCustomersSearchFilter | quote }}
  AUTH_CUSTOMERS_GROUPSEARCH_BASE: {{ .Values.backend.settings.auth.usersCustomersGroupSearchBase | quote }}
  AUTH_CUSTOMERS_GROUPSEARCH_FILTER: {{ .Values.backend.settings.auth.usersCustomersGroupSearchFilter | quote }}
  LDAP_HOST: {{ .Values.backend.settings.ldap.host | quote }}
  LDAP_BIND_DN: {{ .Values.backend.settings.ldap.bindDN | quote }}
