apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ include "vaultMonitoring.fullname" . }}-config
  labels:
    {{- include "vaultMonitoring.labels" . | nindent 4 }}
data:
  vault-agent.hcl: |
    pid_file = "/home/vault/pidfile"

    vault = {
      address = "{{ .Values.vault.scheme }}://{{ .Values.vault.serverName }}"
      ca_cert =  "{{ .Values.vault.ca_path }}"
    }

    auto_auth {
        method "kubernetes" {
            mount_path = "{{ .Values.auth.mount_path }}"
            config = {
                role = "{{ .Values.auth.role }}"
            }
        }

        sink "file" {
            config = {
                path = "/home/vault/config-out/.vault-token"
            }
        }
    }
