{{- if eq .Values.vault.service.type "ExternalName" }}
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    {{- include "vaultMonitoring.labels" . | nindent 4 }}
  name: {{ include "vaultMonitoring.name" . }}
subsets:
- addresses:
  - ip: {{ .Values.vault.ip }}
  ports:
  - name: {{ .Values.vault.portName }}
    port: {{ .Values.vault.port }}
    protocol: TCP
{{- end }}
