{{- if .Values.vault.ca }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "vaultMonitoring.labels" . | nindent 4 }}
  name: {{ include "vaultMonitoring.fullname"  . }}-ca-cert
data:
  ca.crt: {{ .Values.vault.ca | b64enc }}
type: Opaque
{{- end }}
