apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "vaultMonitoring.labels" . | nindent 4 }}
  ## TODO  -- this needs be the same as used in Prom
  name: {{ include "vaultMonitoring.fullname"  . }}-ca-cert
data:
  ca.crt: {{ .Values.vault.ca | b64enc }}
type: Opaque
