# loki-stack -- [loki-stack](https://github.com/grafana/loki) ([example](./examples/loki.yaml))
# @default -- -
lokiStack:
  # lokiStack.enabled -- Enable loki
  enabled: false
  name: loki-stack
  destination:
    # lokiStack.destination.namespace -- Namespace
    namespace: "infra-logging"
  # lokiStack.repoURL -- Repo URL
  # @default -- [repo](https://grafana.github.io/loki/charts)
  repoURL: "https://grafana.github.io/loki/charts"
  # lokiStack.chart -- Chart
  chart: "loki-stack"
  # lokiStack.targetRevision -- [loki-stack Helm chart](https://github.com/grafana/loki/blob/master/production/helm/loki-stack) version
  targetRevision: "2.0.*"
  # lokiStack.values -- Helm values
  # @default -- [upstream values](https://github.com/grafana/loki/blob/master/production/helm/loki-stack/values.yaml)
  values: {}
