apiVersion: v2
name: timed
description: Chart for Timed application
type: application
version: 0.3.11
appVersion: v0.13.2
keywords:
  - timed
  - tracking
home: https://github.com/adfinis-sygroup/timed-frontend
sources:
  - https://github.com/adfinis-sygroup/timed-backend
  - https://github.com/adfinis-sygroup/timed-frontend
  - https://github.com/adfinis-sygroup/helm-charts/tree/master/charts/timed
maintainers:
  - name: adfinis-sygroup
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: postgresql
    version: ~8.7.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
