{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: huawei-csi-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    {{- if .Values.features.resizing.enabled }}
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
    {{- else }}
    verbs: ["get", "list", "watch", "create", "delete"]
    {{- end }}
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    {{- if .Values.features.resizing.enabled }}
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
    {{- else }}
    verbs: ["get", "list", "watch", "update"]
    {{- end }}
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    {{- if .Values.features.snapshotting.enabled }}
    verbs: ["list", "watch", "create", "update", "patch"]
    {{- else }}
    verbs: ["get", "list"]
    {{- end }}
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    {{- if .Values.features.snapshotting.enabled }}
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
    {{- else }}
    verbs: ["get", "list"]
    {{- end }}
  {{- if .Values.features.snapshotting.enabled }}
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status"]
    verbs: ["update"]
  {{- end }}
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: huawei-csi-provisioner-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.controllerName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: huawei-csi-provisioner-runner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: huawei-csi-attacher-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: huawei-csi-attacher-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.controllerName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: huawei-csi-attacher-runner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: huawei-csi-driver-registrar-runner
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: huawei-csi-driver-registrar-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.nodeName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: huawei-csi-driver-registrar-runner
  apiGroup: rbac.authorization.k8s.io

{{- if .Values.features.resizing.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: huawei-csi-resizer-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: huawei-csi-resizer-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.controllerName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: huawei-csi-resizer-runner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: huawei-csi-resizer-cfg
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: huawei-csi-resizer-role-cfg
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.controllerName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: huawei-csi-resizer-cfg
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.features.snapshotting.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: huawei-csi-snapshotter-runner
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: huawei-csi-snapshotter-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.controllerName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: huawei-csi-snapshotter-runner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: huawei-csi-snapshotter-leaderelection
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: huawei-csi-snapshotter-leaderelection
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.controllerName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: huawei-csi-snapshotter-leaderelection
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshot-controller-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status"]
    verbs: ["update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snapshot-controller-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.controllerName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: snapshot-controller-runner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: snapshot-controller-leaderelection
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: snapshot-controller-leaderelection
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.controllerName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: snapshot-controller-leaderelection
  apiGroup: rbac.authorization.k8s.io

---
{{- end }}

{{- end }}
