apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
{{ template "common.metadata" $ }}
spec:
  provider: {{ required "Specify a valid provider." .Values.provider }}
  {{- if .Values.parameters }}
  parameters:
    {{-  tpl .Values.parametersTpl . | nindent 4 }}
  {{- end }}
  {{- if .Values.secretObjects }}
  secretObjects:
    {{- tpl .Values.secretObjectsTpl . | nindent 4 }}
  {{- end }}
