ingress:
  enabled: true
  hostname: <hostname>

  annotations:
    "kubernetes.io/ingress.class": nginx
    "cert-manager.io/issuer": sentry-issuer
    "nginx.ingress.kubernetes.io/proxy-body-size": 0

  tls:
    - hosts:
        - <hostname>
      secretName: sentry-tls

postgresl:
  postgresqlPassword: change-me

system:
  secretKey: chamge-me
