# downscaler -- [kube-downscaler](https://github.com/hjacobs/kube-downscaler) ([example](./examples/kube-downscaler.yaml))
# @default -- -
downscaler:
  # downscaler.enabled -- Enable kube-downscaler
  enabled: false
  destination:
    # downscaler.destination.namespace -- Namespace
    namespace: "infra-downscaler"
  # downscaler.repoURL -- Repo URL
  # @default -- [repo](https://charts.helm.sh/incubator/)
  repoURL: "https://charts.helm.sh/incubator/"
  # downscaler.chart -- Chart
  chart: "kube-downscaler"
  # downscaler.targetRevision -- [kube-downscaler Helm chart](https://github.com/helm/charts/tree/master/incubator/kube-downscaler) version
  targetRevision: "0.5.*"
  # downscaler.values -- Helm values
  # @default -- [upstream values](https://github.com/helm/charts/blob/master/incubator/kube-downscaler/values.yaml)
  values: {}

# signalilo -- [sigalilo](https://github.com/vshn/signalilo) ([example](./examples/signalilo.yaml))
# @default -- -
signalilo:
  # signalilo.enabled -- Enable signalilo
  enabled: false
  destination:
    # signalilo.destination.namespace -- Namespace
    namespace: "infra-signalilo"
  # signalilo.repoURL -- Repo URL
  # @default -- [repo](https://charts.appuio.ch)
  repoURL: "https://charts.appuio.ch"
  # signalilo.chart -- Chart
  chart: "signalilo"
  # signalilo.targetRevision -- [signalilo Helm chart](https://github.com/appuio/charts/tree/master/signalilo) version
  targetRevision: "0.5.*"
  # signalilo.values -- Helm values
  # @default -- [upstream values](https://github.com/appuio/charts/blob/master/signalilo/values.yaml)
  values: {}

# sentryKubernetes -- [sentry-kubernetes](https://github.com/getsentry/sentry-kubernetes) ([example](./examples/sentry-kubernetes.yaml)
# @default -- -
sentryKubernetes:
  # sentryKubernetes.enabled -- Enable sentry-kubernetes
  enabled: false
  destination:
    # sentryKubernetes.destination.namespace -- Namespace
    namespace: "infra-sentry-kubernetes"
  # sentryKubernetes.repoURL -- Repo URL
  # @default -- [repo](https://sentry-kubernetes.github.io/charts)
  repoURL: "https://sentry-kubernetes.github.io/charts"
  # sentryKubernetes.chart -- Chart
  chart: "sentry-kubernetes"
  # sentryKubernetes.targetRevision -- [sentry-kubernetes Helm chart](https://github.com/sentry-kubernetes/charts/tree/develop/sentry-kubernetes)
  targetRevision: "0.3.*"
  # sentryKubernetes.values -- Helm values
  # @default -- [upstream values](https://github.com/sentry-kubernetes/charts/blob/develop/sentry-kubernetes/values.yaml)
  values: {}
