apiVersion: v2
name: rmd
description: Chart for Rmd.io application
type: application
version: 0.1.2
appVersion: edge
keywords:
  - rmd
  - postgresql
home: https://github.com/trowik/rmd.io/tree/fix-uwsgi
sources:
  - https://github.com/trowik/rmd.io/tree/fix-uwsgi
  - https://github.com/trowik/helm-charts/tree/master/charts/rmd
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: postgresql
    version: ~9.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
