metallb:
  enabled: true
  project: infra-metallb
  values:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 192.168.1.10-192.168.1.20
