apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "openshift-etcd-backup.fullname" . }}-use-privileged-scc
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - privileged
