apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "openshift-etcd-backup.fullname" . }}-sa-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "openshift-etcd-backup.fullname" . }}-use-privileged-scc
subjects:
  - kind: ServiceAccount
    name: {{ include "openshift-etcd-backup.serviceAccountName" . }}
