# Make kured cordon drain and reboot nodes that need it

kured:
  enabled: true
  values:
    nodeSelector:
      # kured only works on/for Linux nodes
      kubernetes.io/os: linux
    service:
      # create service for the metrics endpoint
      create: true
    metrics:
      # create a ServiceMonitor for kube-prometheus-stack
      create: true
      labels:
        prometheus: kube-prometheus
