apiVersion: v2
name: argoconfig
description: Configure Argo CD AppProjects, Applications and more
type: application
version: 0.5.1
appVersion: latest
home: https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/
sources:
  - https://github.com/adfinis-sygroup/helm-charts/tree/master/charts/argoconfig
maintainers:
  - name: adfinis-sygroup
    email: support@adfinis.com
    url: https://adfinis.com
