# nameOverride -- Override names
nameOverride: ""

# fullnameOverride -- Override fullname
fullnameOverride: ""

# clusters -- Argo CD cluster secrets
# @default -- see [docs](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#clusters)
clusters:
  defaults:
    # clusters.defaults.enabled -- Enable creating cluster secret
    enabled: false
    # clusters.defaults.namespace -- Namespace to put the cluster config secret into
    namespace: argocd
    # clusters.defaults.config -- Cluster config
    config: {}
  local:
    # clusters.local.enabled -- Local cluster is enabled by default
    enabled: true
    # clusters.local.server -- Cluster API endpoint
    # @default -- Local cluster
    server: https://kubernetes.default.svc
    config: {}
