apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "barman.fullname" . }}-config
  labels:
    {{- include "barman.labels" . | nindent 4 }}
data:
  BARMAN_BACKUP_SCHEDULE: {{ .Values.barman.backupSchedule | quote }}
