apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "barman.fullname" . }}
  labels:
    {{- include "barman.labels" . | nindent 4 }}
spec:
  serviceName: {{ template "barman.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "barman.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        {{- include "barman.labels" . | nindent 8 }}
    spec:
      containers:
        - name: barman
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{/*
          Fix permissions & owner of .pgpass file
          https://www.postgresql.org/docs/9.4/libpq-pgpass.html
          */}}
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "HOME=/home/barman && cp /.pgpass $HOME/ && chown barman:barman $HOME/.pgpass && chmod 600 $HOME/.pgpass"
          envFrom:
            - configMapRef:
                name: {{ include "barman.fullname" . }}-config
          volumeMounts:
            - mountPath: /var/lib/barman
              name: data
              subPath: data
            - mountPath: /var/lib/barman/recover
              name: recover
              subPath: recover
            - mountPath: /etc/barman/barman.d
              name: barman-backups-config
            - mountPath: /etc/barman.conf
              name: barman-global-config
              subPath: barman.conf
            - mountPath: /.pgpass
              name: barman-pgpass-secret
              subPath: .pgpass
            - mountPath: /etc/cron.d/barman
              name: barman-cron-config
              subPath: barman
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if not .Values.persistence.data.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- if not .Values.persistence.recover.enabled }}
        - name: recover
          emptyDir: {}
        {{- end }}
        - name: barman-backups-config
          configMap:
            name: {{ include "barman.fullname" . }}-backups-config
        - name: barman-global-config
          configMap:
            name: {{ include "barman.fullname" . }}-global-config
        - name: barman-pgpass-secret
          secret:
            secretName: {{ include "barman.fullname" . }}-pgpass-secret
            defaultMode: 0600
        - name: barman-cron-config
          configMap:
            name: {{ include "barman.fullname" . }}-cron-config
    {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
  {{- if or .Values.persistence.data.enabled .Values.persistence.recover.enabled }}
  volumeClaimTemplates:
    {{- if .Values.persistence.data.enabled }}
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.persistence.data.accessMode | quote }}
      {{- if .Values.persistence.data.storageClass }}
        storageClassName: {{ .Values.persistence.data.storageClass | quote }}
      {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.data.size | quote }}
    {{- end }}
    {{- if .Values.persistence.recover.enabled }}
    - metadata:
        name: recover
      spec:
        accessModes:
          - {{ .Values.persistence.recover.accessMode | quote }}
      {{- if .Values.persistence.recover.storageClass }}
        storageClassName: {{ .Values.persistence.recover.storageClass | quote }}
      {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.recover.size | quote }}
    {{- end }}
  {{- end }}
