apiVersion: v2
name: storage-apps
description: Argo CD app-of-apps config for storage applications
type: application
# version and appVersion are in sync in this chart!
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/adfinis-sygroup/helm-charts/tree/master/charts/storage-apps
sources:
  - https://github.com/adfinis-sygroup/helm-charts
maintainers:
  - name: adfinis-sygroup
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: argoconfig
    version: 0.7.2
    repository: https://charts.adfinis.com
