{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "osschallenge.fullname" . }}
  labels:
    {{- include "osschallenge.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  accessModes:
  {{ .Values.persistence.accessModes | toYaml | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end -}}
