apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osschallenge.fullname" . }}
  labels:
    {{- include "osschallenge.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.osschallenge.service.secret }}
  DJANGO_SECRET_KEY: {{ .Values.osschallenge.settings.secret | b64enc | quote }}
  {{ else }}
  DJANGO_SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
  EMAIL_HOST_PASSWORD: {{ .Values.osschallenge.settings.emailPassword | b64enc | quote }}
