apiVersion: v1
kind: Service
metadata:
  name: {{ include "osschallenge.fullname" . }}
  labels:
    {{- include "osschallenge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.osschallenge.service.type }}
  ports:
    - port: {{ .Values.osschallenge.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "osschallenge.selectorLabels" . | nindent 4 }}
