name: Lint and Test Charts

on:
  pull_request:
  push:
    branches:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2

    - name: Setup environment for pre-commit
      run: hack/ci/github/setup/pre-commit.sh

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - uses: pre-commit/action@v1.0.1

  lint-test:
    name: Lint and Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Helm version
        run: source .env && echo helm_version=$ADFINIS_CHARTS_HELM_VERSION >> $GITHUB_ENV

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v${{env.helm_version}}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct --config=hack/chart-testing/ct.yaml list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct --config=hack/chart-testing/ct.yaml lint

      - name: Set kind version
        run: source .env && echo kind_version=$ADFINIS_CHARTS_KIND_VERSION >> $GITHUB_ENV
        if: steps.list-changed.outputs.changed == 'true'

      - name: Create kind cluster
        uses: helm/kind-action@v1.1.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          node_image: kindest/node:v${{env.kind_version}}

      - name: Setup cluster for chart-testing (install)
        run: hack/deploy/init.sh
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct --config=hack/chart-testing/ct-install.yaml install
